services:
  lb:
    image: nginx
    ports:
      - "80:80"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data/db


  